config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'welcome/index'
  resources :articles
  resources :logins
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true,
                      length: { minimum: 5 }
  end

app/models/login.rb
class Login < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    def new
        @article = Article.new
    end
    def edit
        @article = Article.find(params[:id])
    end
    def create
        @article = Article.new(params.require(:article).permit(:title, :text))
        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end
    
    def update            
        @article = Article.find(params[:id])
       
        if @article.update(article_params)
          redirect_to @article
        else
          render 'edit'
        end
      end
    def show
        @article = Article.find(params[:id])
    end
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
       
        redirect_to articles_path
      end
    private
    def article_params
        params.require(:article).permit(:title, :text)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    def index
        @logins = Login.all
    end
    def new
        @logins = Login.new
    end
    def edit
        @logins = Login.find(params[:id])
    end
    def create
        @logins = Login.new(params.permit(:loginname, :password))
        if @logins.save
            redirect_to @logins
        else
            render 'new'
        end
    end
    
    def update            
        
    end
    def show
        @logins = Login.find(params[:id])
    end
    def destroy
        
      end
    private
    def article_params
        
    end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/articles/_forw.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title ,class:'warning'%><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 <%= render 'forw' %>
<%= link_to 'Back', articles_path ,"history.back()"%>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= render 'forw' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Back', articles_path %>

<script type="text/javascript">
      window.onpageshow = function(evt) {
        // If persisted then it is in the page cache, force a reload of the page.
        if (evt.persisted) {
          document.body.style.display = "none";
          location.reload();
        }
      };
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MysqlApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/index.html.erb
<%= form_with model: @login, local: true do |form| %>
<div id="MainDiv">
<h1>Login</h1>
<div id="LoginDiv">
<p>
    <%= form.text_field :loginname ,placeholder: "LoginName"%>
  </p>
 
  <p>    
    <%= form.text_field :password ,placeholder: "Password"%>
  </p>
 
  <p>
    <%= form.submit:"Login" %>
  </p>
</div></div>
<% end %>

app/views/logins/show.html.erb
<p>
  <strong>loginname:</strong>
  <%= @logins.loginname %>
</p>
 
<p>
  <strong>password:</strong>
  <%= @logins.password %>
</p>
<%= link_to 'Back', logins_path %>

<script type="text/javascript">
      window.onpageshow = function(evt) {
        // If persisted then it is in the page cache, force a reload of the page.
        if (evt.persisted) {
          document.body.style.display = "none";
          location.reload();
        }
      };
    </script>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>